- src/main/resources/application.properties
I Have Clone A Project Then I have create a New Branch MaheshM. I am Push Branch for cheking for conflict.
> My First Commit

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Purchase.java
- src/main/java/com/billing/services/CustomerServiceImpl.java
- src/main/java/com/billing/services/ProductServices.java
- src/main/java/com/billing/services/SupplierServiceImpl.java
- src/main/resources/templates/admin/add_supplier.html
- src/main/resources/templates/admin/customer_list.html
- src/main/resources/templates/admin/purchasebill_add.html
- src/main/resources/templates/admin/purchasebill_list.html
- src/main/resources/templates/fragments/sidebar.html
1. I have created two get API's in admin controller for purchasebill_list & purchasebill_add to render pages on browser
2. In templete -> Admin -> I have created purchasebill_list.html & purchasebill_add.html file
3. In sidebar I have made changes in Purchasebill button's path -> given API's Path
4. Updated admin controller to render Active customers and Active Suppliers on Dashboard from database Dynamically
5. In Sidebar, changed icon's for all the fields like Product, sale, Purchase, Finance & Account, Stock, Peoples & Master etc...
> Commit by Younus on 19 April 2024

- src/main/java/com/billing/controller/adminController.java
- src/main/resources/templates/admin/view_Admin_Profile.html
- src/main/resources/templates/fragments/header.html
Changes:-
1. I have create a new  method in controller which name is viewAdminProfile.
2. I have create a new html page which has name is view_admin_profile.
3. I have change in header.html there i have write a controller link in the button.
> changes in view admin profile

- src/main/java/com/billing/controller/adminController.java
- src/main/resources/templates/admin/add_parties.html
- src/main/resources/templates/admin/add_supplier.html
- src/main/resources/templates/admin/parties_list.html
- src/main/resources/templates/admin/supplier_list.html
- src/main/resources/templates/admin/transactions_list.html
- src/main/resources/templates/admin/update_supplier.html
- src/main/resources/templates/admin/update_transactions.html
- src/main/resources/templates/admin/view_Admin_Profile.html
1. i have change UI part of add supplier, update supplier, add parties, update parties, and view admin profile.
> Some frontend changes.

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/repositories/CompanyRepository.java
- src/main/java/com/billing/repositories/CustomerRepository.java
- src/main/java/com/billing/services/CustomerService.java
- src/main/java/com/billing/services/CustomerServiceImpl.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/add_product_form.html
- src/main/resources/templates/admin/sales_list.html
- src/main/resources/templates/admin/update_supplier.html
- src/main/resources/templates/admin/view_Admin_Profile.html
- src/main/resources/templates/fragments/sidebar.html
1. I have create a sales list page.
2. I have change Design of sale list page.
> changes in sales list page and we change design of pages

- .gitignore
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Parties.java
- src/main/resources/templates/admin/add_parties.html
- src/main/resources/templates/admin/update_Admin_Profile.html
- src/main/resources/templates/admin/update_parties.html
- src/main/resources/templates/admin/view_Admin_Profile.html
- src/main/resources/templates/fragments/header.html
- src/main/resources/templates/users/loginform.html
1. I have worked on the view admin profile and update Admin profile.
2. In that page i have worked on the styling of the pages.
3. Also I have worked on when an image is present in the database but not in folder then that time it doesn't show anything.
4. I have solved this problem now it will show the admin profile in default.
5. Also i have create a parties class.
> commit on 30/05/2024

- src/main/resources/templates/fragments/base.html
- src/main/resources/templates/fragments/sidebar.html
- src/main/resources/templates/home.html
1.  In Master Module I have created Add Charges Model
2. In sidebar.html page I have added Report Module that contains fields like 1. Sales Report 2. Purchase Report 3. Tax Report and 4. Profit & Loss Module
> Commit by Younus on 29/05/2024

- src/main/resources/templates/fragments/sidebar.html
> Changes by Younus on 31/05/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Customer.java
- src/main/java/com/billing/model/Product.java
- src/main/java/com/billing/model/Sales.java
- src/main/java/com/billing/repositories/SalesRepository.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/sales_add.html
- src/main/resources/templates/admin/sales_list.html
1. I have worked on the Sales bill module.
2. I have created a Sales Class and created a table in the database.
3. Now the user is able to create a Sales bill and also data is stored in the database. 
4. All sales lists are shown on the Sales list page.
5. And user want to delete the sales bill then this is also done.
> commit by Mahesh on 03/06/2024

- src/main/java/com/billing/controller/adminController.java
> commit by Younus on 04/06/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/manage_stock.html
- src/main/resources/templates/home.html
1. I have worked on the home page.
2. In the home page I have shown the table of sales records and purchase order records.
3. Also work on when a user created a sales bill that time needs to enter the tax percentage manually now we take from the table.
> commit by Mahesh on 10/06/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/PartiesTransaction.java
- src/main/resources/templates/admin/customer_list.html
- src/main/resources/templates/admin/product_list.html
- src/main/resources/templates/admin/purchase_Report.html
- src/main/resources/templates/admin/purchasebill_add.html
- src/main/resources/templates/fragments/sidebar.html
1. I have made changes in Product module and Purchase bill module -> now user is able to purchase the product & that will be updated in  stock.
2. I have also worked on Reports module in that I have created Purchase report page, Now we have shown all the purchase bill  transections on Purchase Report successfully.
> commit by Younus on 10/06/2024

- src/main/resources/templates/admin/product_list.html
- src/main/resources/templates/admin/purchasebill_add.html
- src/main/resources/templates/admin/purchasebill_transection.html
- src/main/resources/templates/fragments/sidebar.html
1. I have Worked on PurchaseBill Module, In that I have added Bill number Functionality , Now Bill number will be generated automatically.
2. I have also worked on the sidebar.html page in that I have changed the title of all Modules
> Changes by Younus on 11/06/2024

- src/main/java/com/billing/A2zbillingApplication.java
- src/main/java/com/billing/controller/PartiesController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/add_parties.html
- src/main/resources/templates/admin/parties_list.html
- src/main/resources/templates/admin/sales_add.html
- src/main/resources/templates/admin/sales_list.html
- src/main/resources/templates/admin/transactions_list.html
- src/main/resources/templates/admin/update_parties.html
- src/main/resources/templates/fragments/sidebar.html
- src/main/resources/templates/home.html
- src/main/resources/templates/users/loginform.html
1. I have worked on a login page. I have added a link in Instagram, Google, Linkedin and Facebook.
2. And also do the styling in that page.
3. I have worked on the home page. In that I have give the styling for the Minimum Stock Alert.
4. Also I have worked on the party page. I have changed the name of all the parties to supplier.
> commit by Mahesh on 13/06/2024

- src/main/java/com/billing/controller/CustomerController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/repositories/SalesRepository.java
- src/main/resources/templates/admin/parties_list.html
- src/main/resources/templates/admin/sales_add.html
- src/main/resources/templates/admin/sales_return.html
1. I have worked on sales page. In that i have do the styling.
> commit by mahesh on 15/06/2024

- src/main/java/com/billing/controller/PartiesController.java
- src/main/java/com/billing/controller/ProductController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Parties.java
- src/main/java/com/billing/model/PartiesTransaction.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/add_product_form.html
- src/main/resources/templates/admin/edit_product.html
- src/main/resources/templates/admin/manage_stock.html
- src/main/resources/templates/admin/product_list.html
- src/main/resources/templates/admin/purchase_Tax_Report.html
- src/main/resources/templates/admin/purchasebill_add.html
- src/main/resources/templates/admin/purchasebill_transection.html
- src/main/resources/templates/admin/sales_Tax_Report.html
- src/main/resources/templates/admin/transactions_list.html
- src/main/resources/templates/admin/update_parties.html
- src/main/resources/templates/home.html
1. I have worked on add product page and update product page In that have add the validations like user need to add the supplier, and when user add the product that time need to add brand, category, color otherwise it will give error now user not select then also it will not give error.
2. I have worked on supplier page(parties) and purchase page in that when user purchase the any product that due is remaining that due is minus from the suppliers(parties) amount and updated amount is show in suppliers list.
3. if suppliers(parties) amount is negative then in column it will show toReceive otherwise toPay.
> commit1 by mahesh on 18/06/2024

- src/main/java/com/billing/controller/CustomerController.java
- src/main/java/com/billing/controller/PartiesController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Customer.java
- src/main/java/com/billing/model/Sales.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/add_parties.html
- src/main/resources/templates/admin/customer_list.html
- src/main/resources/templates/admin/sales_add.html
- src/main/resources/templates/admin/sales_list.html
- src/main/resources/templates/admin/sales_return.html
- src/main/resources/templates/admin/update_parties.html
1. I have worked on a customer model in that i have added a new Due Amount field.
2. I have worked on the Sales add page in that  I have worked when any customer due amount is remaining that time this will add to customer due.
3. Also I have worked on Sales return or update page in that user update a sales bill that time product quantity is updated and due is also updated.
> commit by mahesh on 19/06/2024

- src/main/java/com/billing/controller/LoginController.java
- src/main/resources/application.properties
- src/main/resources/templates/users/loginform.html
1. I have worked on a login page that I have worked on when the user wants to create a new account At that time we added the email verification. 
2. When users add email and also give button for sending OTP to give mail. After send OTP  message will show "OTP send Successfully!!" And for enter OTP input field and the verify button will show.
3. When click on Verify button then if enter OTP is correct then the message shows "Email verified Successfully!!"  Otherwise "please enter correct OTP !! ".
> commit by mahesh on 21/06/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/resources/templates/fragments/sidebar.html
Modified Finance & Account module to Cash & Accounts - under that added 1. Cash in Hand 2. Cheque payment 3. Online Payment
> commit by Younus on 25/06/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Sales.java
- src/main/java/com/billing/repositories/SalesRepository.java
- src/main/resources/templates/admin/sales_list.html
- src/main/resources/templates/fragments/sidebar.html
1. I have worked on sale model.
2. In sale model i have add new field saleType.
3. when user create new sale bill that time saleType is **Sale**.
4. And when user is return any Product that time saleType is **Return**.
5. After that return sale list will show on new page.
> commit by mahesh on 28/06/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/repositories/SalesRepository.java
- src/main/resources/application.properties
- src/main/resources/templates/admin/saleReturnList.html
- src/main/resources/templates/admin/sales_return.html
1. I have worked on a sales Return module.
2. When the user returns any product or decreases the quantity of product that time this product will add in sales return transaction.
3. But if the user edits the customer or increases the quantity of product or adds a new product that time this sale does not add in sales return transaction.
4. And also added a button for deleting a sales return transaction.
> commit by mahesh on 01/07/2024

- src/main/resources/templates/admin/add_parties.html
- src/main/resources/templates/admin/add_product_form.html
- src/main/resources/templates/admin/brand_list.html
- src/main/resources/templates/admin/categories_list.html
- src/main/resources/templates/admin/parties_list.html
- src/main/resources/templates/admin/product_list.html
- src/main/resources/templates/admin/profit_And_Loss_Report.html
- src/main/resources/templates/users/loginform.html
I have Worked on
1.  Profit & Loss report
2. Changed Login page Title and Logo
3. Modified Product, Category and Brand Module
> Commit by Younus on 02/07/2024

- src/main/java/com/billing/controller/ProductController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Sales.java
- src/main/resources/templates/admin/Registration.html
- src/main/resources/templates/admin/add_parties.html
- src/main/resources/templates/admin/add_supplier.html
- src/main/resources/templates/admin/cashPaymentList.html
- src/main/resources/templates/admin/chequePaymentList.html
- src/main/resources/templates/admin/manage_stock.html
- src/main/resources/templates/admin/onlinePaymentList.html
- src/main/resources/templates/admin/parties_list.html
- src/main/resources/templates/admin/saleReturnList.html
- src/main/resources/templates/admin/sales_add.html
- src/main/resources/templates/admin/sales_list.html
- src/main/resources/templates/admin/sales_return.html
- src/main/resources/templates/admin/transactions_list.html
- src/main/resources/templates/admin/update_Admin_Profile.html
- src/main/resources/templates/admin/update_parties.html
- src/main/resources/templates/admin/view_Admin_Profile.html
1. I have worked on Sales Return Module in that I have show return product netPayment and it status for cheking a amount paid or not.
2. I have worked on Styling the heading of some pages.
> commit by Mahesh on 02/07/2024

- src/main/java/com/billing/controller/adminController.java
> commit by Younus

- src/main/java/com/billing/controller/CustomerController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Customer.java
- src/main/java/com/billing/model/User.java
- src/main/resources/templates/admin/customer_list.html
- src/main/resources/templates/home.html
1. I have worked on the home page. 
2. In that I have shown an alert message and alert message scroll from left to right.
3. This alert message shows when the customer due amount is greater than 0 and Who missed the payment deadline.
> commit by mahesh on 06/07/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Brand.java
- src/main/java/com/billing/model/Expense.java
- src/main/java/com/billing/model/User.java
- src/main/java/com/billing/repositories/ExpenseRepository.java
- src/main/resources/templates/admin/add_expense.html
- src/main/resources/templates/admin/expense_list.html
- src/main/resources/templates/admin/purchaseorder_add.html
- src/main/resources/templates/fragments/sidebar.html
1. I have worked on Expense module in that I have created two API's to render Expense list page and Add Expense page...
2. I have also added delete functionality in Purchase Order Module
> commit by Younus on 7/7/2024

- src/main/java/com/billing/controller/CustomerController.java
- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/repositories/ExpenseRepository.java
- src/main/resources/templates/admin/profit_And_Loss_Report.html
Changes in profit and loss report
> commit by Mahesh on 10/07/2024

- src/main/resources/application.properties
- src/main/resources/templates/admin/profit_And_Loss_Report.html
> Commit by Younus on 10/07/2024

- src/main/java/com/billing/controller/adminController.java
- src/main/java/com/billing/model/Product.java
- src/main/resources/templates/admin/manage_stock.html
- src/main/resources/templates/admin/sales_add.html
1. I have added a new field in the product whose name is selling price.
2. User need to add the selling price of the product in manage Stock.
3. At the time of Sale the product selling price is empty then it will take the purchase price.
> commit by Mahesh on 11/07/2024

- src/main/java/com/billing/model/Brand.java
- src/main/java/com/billing/model/Category.java
- src/main/java/com/billing/model/Company.java
- src/main/java/com/billing/model/Customer.java
- src/main/java/com/billing/model/GSTRate.java
- src/main/java/com/billing/model/Product.java
- src/main/java/com/billing/model/Supplier.java
- src/main/java/com/billing/model/Unit.java
- src/main/java/com/billing/model/User.java
- src/main/resources/templates/admin/update_Admin_Profile.html
> commit by mahesh on 12/07/2024
